version: "3.9"  # optional since v1.27.0
services:
  goloop:
    container_name: tutorial_goloop
    build:
      context: .
      args:
        BTPSIMPLE_VERSION: latest
        GOLOOP_IMAGE: iconloop/goloop:latest
    ports:
      - "9080:9080"
    volumes:
      - config:/goloop/config
      - data:/goloop/data
      - ./logs:/goloop/data/log
    environment:
      - GOLOOP_NODE_DIR=/goloop/data/goloop
      - GOLOOP_LOG_WRITER_FILENAME=/goloop/data/log/goloop.log
  btpsimple_src:
    container_name: tutorial_btpsimple_src
    image: btpsimple:latest
    security_opt:
      - seccomp:unconfined
    ports:
      - "10080:40000"
    volumes:
      - ../cmd:/btpsimple/cmd
      - ../common:/btpsimple/common
      - config:/btpsimple/config
      - data:/btpsimple/data
      - ./logs:/btpsimple/data/log
    environment:
      - BTPSIMPLE_BASE_DIR=/btpsimple/data/btpsimple_src
      - BTPSIMPLE_CONFIG=/btpsimple/config/src.config.json
      - BTPSIMPLE_SRC_ADDRESS_FILE=/btpsimple/config/btp.src
      - BTPSIMPLE_SRC_ENDPOINT=http://goloop:9080/api/v3/src
      - BTPSIMPLE_DST_ADDRESS_FILE=/btpsimple/config/btp.dst
      - BTPSIMPLE_DST_ENDPOINT=http://goloop:9080/api/v3/dst
      - BTPSIMPLE_OFFSET_FILE=/btpsimple/config/offset.src
      - BTPSIMPLE_KEY_STORE=/btpsimple/config/src.ks.json
      - BTPSIMPLE_KEY_SECRET=/btpsimple/config/src.secret
      - BTPSIMPLE_LOG_WRITER_FILENAME=/btpsimple/data/log/btpsimple_src.log
    links:
      - goloop
  btpsimple_dst:
    container_name: tutorial_btpsimple_dst
    image: btpsimple:latest
    security_opt:
      - seccomp:unconfined
    ports:
      - "10081:40000"
    volumes:
      - ../cmd:/btpsimple/cmd
      - ../common:/btpsimple/common
      - config:/btpsimple/config
      - data:/btpsimple/data
      - ./logs:/btpsimple/data/log
    environment:
      - BTPSIMPLE_BASE_DIR=/btpsimple/data/btpsimple_dst
      - BTPSIMPLE_CONFIG=/btpsimple/config/dst.config.json
      - BTPSIMPLE_SRC_ADDRESS_FILE=/btpsimple/config/btp.dst
      - BTPSIMPLE_SRC_ENDPOINT=http://goloop:9080/api/v3/dst
      - BTPSIMPLE_DST_ADDRESS_FILE=/btpsimple/config/btp.src
      - BTPSIMPLE_DST_ENDPOINT=http://goloop:9080/api/v3/src
      - BTPSIMPLE_OFFSET_FILE=/btpsimple/config/offset.dst
      - BTPSIMPLE_KEY_STORE=/btpsimple/config/dst.ks.json
      - BTPSIMPLE_KEY_SECRET=/btpsimple/config/dst.secret
      - BTPSIMPLE_LOG_WRITER_FILENAME=/btpsimple/data/log/btpsimple_dst.log
    links:
      - goloop
volumes:
  config: {}
  data: {}     