version: "3.9"  # optional since v1.27.0
services:
  goloop:
    build:
      context: .
      args:
        BTPSIMPLE_VERSION: latest
        GOLOOP_IMAGE: iconloop/goloop:0.9.5
    ports:
      - "9080:9080"
    volumes:
      - config:/goloop/config
      - data:/goloop/data
    environment:
      - GOLOOP_NODE_DIR=/goloop/data/goloop
      - GOLOOP_LOG_WRITER_FILENAME=/goloop/data/log/goloop.log
  btpsimple_src:
    image: btpsimple:latest
    volumes:
      - config:/btpsimple/config
      - data:/btpsimple/data
    environment:
      - BTPSIMPLE_BASE_DIR=/btpsimple/data/btpsimple_src
      - BTPSIMPLE_CONFIG=/btpsimple/config/src.config.json
      - BTPSIMPLE_SRC_ADDRESS=/btpsimple/config/btp.src
      - BTPSIMPLE_SRC_ENDPOINT=http://goloop:9080/api/v3/src
      - BTPSIMPLE_DST_ADDRESS=/btpsimple/config/btp.dst
      - BTPSIMPLE_DST_ENDPOINT=http://goloop:9080/api/v3/dst
      - BTPSIMPLE_OFFSET=/btpsimple/config/offset.src
      - BTPSIMPLE_KEY_STORE=/btpsimple/config/src.ks.json
      - BTPSIMPLE_KEY_SECRET=/btpsimple/config/src.secret
      - BTPSIMPLE_LOG_WRITER_FILENAME=/btpsimple/data/log/btpsimple_src.log
    links:
      - goloop
  btpsimple_dst:
    image: btpsimple:latest
    volumes:
      - config:/btpsimple/config
      - data:/btpsimple/data
    environment:
      - BTPSIMPLE_BASE_DIR=/btpsimple/data/btpsimple_dst
      - BTPSIMPLE_CONFIG=/btpsimple/config/dst.config.json
      - BTPSIMPLE_SRC_ADDRESS=/btpsimple/config/btp.dst
      - BTPSIMPLE_SRC_ENDPOINT=http://goloop:9080/api/v3/dst
      - BTPSIMPLE_DST_ADDRESS=/btpsimple/config/btp.src
      - BTPSIMPLE_DST_ENDPOINT=http://goloop:9080/api/v3/src
      - BTPSIMPLE_OFFSET=/btpsimple/config/offset.dst
      - BTPSIMPLE_KEY_STORE=/btpsimple/config/dst.ks.json
      - BTPSIMPLE_KEY_SECRET=/btpsimple/config/dst.secret
      - BTPSIMPLE_LOG_WRITER_FILENAME=/btpsimple/data/log/btpsimple_dst.log
    links:
      - goloop
volumes:
  config: {}
  data: {}