[package]
name = "test-helper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
workspaces = "0.1.1"
near-crypto = "0.5"
near-primitives = "0.5"
chrono = "0.4.19"
rand = "0.8.4"
futures = "0.3.17"
duplicate = "0.3.0"
serde_json = "^1.0"
anyhow = "1.0"
tokio = { version = "^1.6.0", features = ["full"] }